name: N-Central script testing + deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-en-deploy:
    name: Controleer PowerShell-scripts en zet ze klaar voor N-Central
    runs-on: windows-latest

    steps:
      - name: Haal de code op (checkout)
        uses: actions/checkout@v4

      - name: Voer PSScriptAnalyzer uit op alle .ps1-scripts in de hoofdmap
        shell: pwsh
        run: |
          $scripts = Get-ChildItem -Path . -Filter '*.ps1'
          foreach ($script in $scripts) {
              Write-Host "Analyseren van $($script.FullName)"
              Invoke-ScriptAnalyzer -Path $script.FullName -Severity Error,Warning
          }

      - name: Deploy naar N-Central (Tijdelijk, dit zal eind dit jaar aangepast worden voor een werkend deployment wanneer deze functionaliteit ondersteund wordt door N-Central)
        shell: pwsh
        run: |
          Write-Host "Simuleer deployment naar N-Central..."
          $scripts = Get-ChildItem -Path . -Filter '*.ps1'
          foreach ($script in $scripts) {
              Write-Host "Zou $($script.FullName) deployen naar N-Central."
          }
