name: PowerShell CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-deploy:
    name: Lint PowerShell scripts and deploy to N-Central
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer on all .ps1 scripts in root
        shell: pwsh
        run: |
          $scripts = Get-ChildItem -Path . -Filter '*.ps1'
          foreach ($script in $scripts) {
              Write-Host "Analyzing $($script.FullName)"
              Invoke-ScriptAnalyzer -Path $script.FullName -Severity Error,Warning
          }

      - name: Deploy to N-Central (Placeholder)
        shell: pwsh
        run: |
          Write-Host "Simulating deployment to N-Central..."
          $scripts = Get-ChildItem -Path . -Filter '*.ps1'
          foreach ($script in $scripts) {
              Write-Host "Would deploy $($script.FullName) to N-Central."
          }
