naam: N-Central script testing + deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:

taken:
  lint-en-deploy:
    naam: Controleer PowerShell-scripts en zet ze klaar voor N-Central
    draait-op: windows-latest

    stappen:
      - naam: Haal de code op (checkout)
        gebruikt: actions/checkout@v4

      - naam: Voer PSScriptAnalyzer uit op alle .ps1-scripts in de hoofdmap
        shell: pwsh
        voer uit: |
          $scripts = Get-ChildItem -Path . -Filter '*.ps1'
          foreach ($script in $scripts) {
              Write-Host "Analyseren van $($script.FullName)"
              Invoke-ScriptAnalyzer -Path $script.FullName -Severity Error,Warning
          }

      - naam: Deploy naar N-Central (Tijdelijk, dit zal eind dit jaar aangepast worden voor een werkend deployment wanneer deze functionaliteit ondersteund wordt door N-Central)
        shell: pwsh
        voer uit: |
          Write-Host "Simuleer deployment naar N-Central..."
          $scripts = Get-ChildItem -Path . -Filter '*.ps1'
          foreach ($script in $scripts) {
              Write-Host "Zou $($script.FullName) deployen naar N-Central."
          }
